apiVersion: v1
kind: Service
metadata:
  name: github-readme-activity-graph
  namespace: github-stats
  annotations:
    nodeport-allocation: "manual-allocated-per-plan"
    allocated-date: "2026-09-11"
spec:
  type: NodePort
  selector:
    app: github-readme-activity-graph
  ports:
    - port: 5100
      targetPort: 5100
      nodePort: 30445
      protocol: TCP
