apiVersion: v1
kind: Service
metadata:
  name: github-readme-streak-stats
  namespace: github-stats
  annotations:
    nodeport-allocation: "manual-allocated-per-plan"
    allocated-date: "2026-09-11"
spec:
  type: NodePort
  selector:
    app: github-readme-streak-stats
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30446
      protocol: TCP
