apiVersion: v1
kind: Service
metadata:
  name: github-profile-summary-cards
  namespace: github-stats
  annotations:
    nodeport-allocation: "manual-allocated-per-plan"
    allocated-date: "2026-09-11"
spec:
  type: NodePort
  selector:
    app: github-profile-summary-cards
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30447
      protocol: TCP
