apiVersion: v1
kind: Service
metadata:
  name: github-readme-stats
  namespace: github-stats
  annotations:
    nodeport-allocation: "manual-allocated-per-plan"
    allocated-date: "2026-09-11"
spec:
  type: NodePort
  selector:
    app: github-readme-stats
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30444
      protocol: TCP
